### ISSUE TITLE
Webapp crashes in Internet Explorer 10 [first time]

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/plugins#15]
Hello,
The following Javascript error message occurs when running this web site with IE10:

SCRIPT5007: Unable to get property 'split' of undefined or null reference 
scripts.2d21fa5b.js, line 1 character 286

If we continue running we get this:

![image](https://cloud.githubusercontent.com/assets/7569958/10012023/757e7370-6103-11e5-832a-3bafad1bc6ca.png)

regards,
Tomolimo

**Comment by orthagh** [comment]
@tomolimo, please ensure you browser is not in compatibily mode (render engine in IE<10)

Soon, We'll make some changes to lower the internet explorer version prerequisite. 
IE9 actually crashs on javascript.

**Comment by tomolimo** [comment]
I made tests for all settings, and the error is with all settings...
IE10 -> doc stds
IE10 -> doc Quirks
IE10 -> doc IE9
and
IE10 compat view -> doc stds
IE10 compat view -> doc Quirks
IE10 compat view -> doc IE9
and more
...
One question: Did you test with IE10?

**Comment by ghost** [comment]
@tomolimo 
We are going to work on the fix for IE10, we will notice you when it's ready.
Have you got any possibility to use it with Firefox/Chrome right now ?
Thanks for your understanding

Regards,
Nelson Zamith
Teclib' GLPi Team.

**Comment by tomolimo** [comment]
Don't worry: this is not a problem for me :)

**Comment by ghost** [comment]
@tomolimo  Thanks a lot for reporting !
Reporting is extremely important/useful to us.
Don't hesitate to do so as often as willed !

Regards,
Nelson Zamith

**Comment by tomolimo** [comment]
That's my motto ☺

-------- Original message --------
From: Nelson Zamith
Date:24/09/2015 17:13 (GMT+01:00)
To: glpi-project/plugins
Cc: "Moron, Olivier"
Subject: Re: [plugins] Javascript error message with IE10 (#15)

@tomolimohttps://github.com/tomolimo Thanks a lot for reporting !
Reporting is extremely important/useful to us.
Don't hesitate to do so as often as willed !

Regards,
Nelson Zamith

**Comment by ghost** [comment]
@tomolimo : We're happy at Teclib to announce you that the support for Internet Explorer 10 has been enhanced, there is one small visual glitch spotted on the language selector, but otherwise, the GLPi Plugins directory seems to run in the browser, be certain we will keep on working on the IE support throughout the development process of the Plugins directory.

**Comment by tomolimo** [comment]
Thank you very much,
regards,
Tomolimo

**Comment by ghost** [comment]
Thank you Tomolimo :)
Nelson Z, Teclib GLPi Team
