### ISSUE TITLE
email sent to 'contact' but got no answer

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/plugins#26]
Hello,
As I would like to move the 'Timezones' plugin from the old forge to github (at least for the new versions), and as it is no possible to use the 'Submit a plugin' (as it is already existing), I've sent an email to 'contact' URL http://plugins.glpi-project.org/#/contact, but got no answer.

Thank you to check,
Regards,
Tomolimo

**Comment by ghost** [comment]
Hello Tomolimo,
We're sorry, it has been done now. http://plugins.glpi-project.org/#/plugin/timezones

Regards,
Nelson Z.

**Comment by tomolimo** [comment]
Thank you very much

**Comment by ghost** [comment]
You are very welcome @tomolimo !
Nelson Z.
