### ISSUE TITLE
The link on the repository github description leads to HTTP error 502

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/plugins#27]
Using the URL https://plugins.glpi-project.org/ leads browsers to HTTP 502 error: Bad gateway...
I clicked on the link in front of the https://github.com/glpi-project/plugins and I got this error...
regards,
Tomolimo

**Comment by ghost** [comment]
In fact, I already saw that before : | You 're right, it's there at #21 
Truth is that we don't have https :D we are thinking about that for the upcoming version which is about to need it much more.
You need to go with http:// :)
Thanks,
Newls

**Comment by ghost** [comment]
Oops, you're still right about this link which I don't have hands on, reported internally too.
Thanks again,
Nelson Z.

**Comment by ghost** [comment]
Link edited for now, HTTPS scheme will work as soon as possible.
Thanks for reporting the SEO problem.
Regards,
Nelson Z. @ GLPi Team
