### ISSUE TITLE
Having the supported languages displayed in plugin card

### ISSUE THREAD

**Issue by yllen** [glpi-project/plugins#28]
In XML file we have languages generated by the plugin.
But in catalogue, we don't see which languages the plugin maintains.
I think an user must knows if the plugin is compatible or not with his language

**Comment by ghost** [comment]
Feature has been done in the following commits:

c40026856b9944ec689fd1b346efaa19552e15f8
17a4e177c9c71c02a964fe48a645c59aa02e2429
0d9fc7f2146fd2210363df670b4cda16bbf9cdb1
ed043bb2a5f2761b1af15873a6e2cc7a9a1c52f8
9bb05c36e58183ad87928abd4d9dc25de1b5a95c

It will soon be available on the site.
Thank you for reporting bugs or missing things on glpi-plugin-directory

Regards,
Nelson Z.
