### ISSUE TITLE
Open download link in a new tab

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/plugins#32]
Hi,
The "download" button does not open the page in a new tab.
It would be very useful allow the click-wheel or ctrl + click on this "download" button!
Cheers,

**Comment by ghost** [comment]
Will try to make it possible for middle-click/new-tab-opening on download link !
Cheerz @flegastelois

**Comment by ghost** [comment]
@flegastelois this is done in the development branch, this is soon about to be merged, I should have done this fix in a branch derivative of the master, but the project is running into a pre-prod sum/merge so the fix will be public on the next official release.
Middle-click is now possible on preprod.
