### ISSUE TITLE
Web site is one more time broken with IE10

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/plugins#34]
![image](https://cloud.githubusercontent.com/assets/7569958/10659574/260806b6-78a1-11e5-99f7-2aca6bebcf04.png)

**Comment by tomolimo** [comment]
Error messages found in javascript debugger:

SCRIPT1046: Multiple definitions of a property not allowed in strict mode 
scripts.8e1e1425.js, line 1 character 2828
SCRIPT5022: [$injector:modulerr] Failed to instantiate module frontendApp due to:
Error: [$injector:nomod] Module 'frontendApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=frontendApp
   at Anonymous function (http://plugins.glpi-project.org/scripts/vendor.0f218e37.js:3:30162)
   at b (http://plugins.glpi-project.org/scripts/vendor.0f218e37.js:3:29622)
   at Anonymous function (http://plugins.glpi-project.org/scripts/vendor.0f218e37.js:3:29896)
   at Anonymous function (http://plugins.glpi-project.org/scripts/vendor.0f218e37.js:4:6627)
   at f (http://plugins.glpi-project.org/scripts/vendor.0f218e37.js:3:21016)
   at n (http://plugins.glpi-project.org/scripts/vendor.0f218e37.js:4:6470)
   at $a (http://plugins.glpi-project.org/scripts/vendor.0f218e37.js:4:8158)
   at h (http://plugins.glpi-project.org/scripts/vendor.0f218e37.js:3:27689)
   at ga (http://plugins.glpi-project.org/scripts/vendor.0f218e37.js:3:27908)
   at fa (http://plugins.glpi-project.org/scripts/vendor.0f218e37.js:3:27253)
http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=frontendApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'frontendApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.7%2F%24injector%2Fnomod%3Fp0%3DfrontendApp%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.0f218e37.js%3A3%3A30162)%0A%20%20%20at%20b%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.0f218e37.js%3A3%3A29622)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.0f218e37.js%3A3%3A29896)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.0f218e37.js%3A4%3A6627)%0A%20%20%20at%20f%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.0f218e37.js%3A3%3A21016)%0A%20%20%20at%20n%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.0f218e37.js%3A4%3A6470)%0A%20%20%20at%20%24a%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.0f218e37.js%3A4%3A8158)%0A%20%20%20at%20h%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.0f218e37.js%3A3%3A27689)%0A%20%20%20at%20ga%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.0f218e37.js%3A3%3A27908)%0A%20%20%20at%20fa%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.0f218e37.js%3A3%3A27253) 
vendor.0f218e37.js, line 4 character 6795

**Comment by ghost** [comment]
Yep, it was previsible, a lot has changed in the production version. I'm already working on that fix.  
I hope it's gonna be allright as soon as possible for Internet Explorer users.
Thanks for reporting bugs @tomolimo !
Nelson Z. @ Teclib'

**Comment by tomolimo** [comment]
You're welcome
And if you need me to test or to debug something just tell it.

**Comment by ghost** [comment]
@tomolimo the fix has been deployed.
I hope it is working.
Currently the OAuth2 feature which enables users to register via their github account, or simply having the external account linked to GLPi Plugins account, is not available on IE, I'll create another ticket for that as it's a bigger issue in terms of scope.

Please tell me if you are able to browse the directory with IE 10 !
It currently works on my VM but I would enjoy your return !

**Comment by tomolimo** [comment]
Yes, thank you, it ok now:
![image](https://cloud.githubusercontent.com/assets/7569958/10663885/5280e44c-78bf-11e5-9465-714c1701a875.png)
But if I may suggest: when the windows is too small, the part on the right side disappears :( so that you don't even know that it is existing :(. And a click on the small menu icon does nothing! Behaviour is the same with Chrome

**Comment by ghost** [comment]
It's true there is still a lot to improve on the frontend-side.  
It's all the work coming along with the development of our specific backend which took time.
Hopefully we're going to be focused on the frontend more now.

Actually, it's the 3 white lines, at the top-right corner of the window, that are responsible for showing the right-sided navbar which you talk about, when screen width is not large enough to show it.

Good to have your review, thanks @tomolimo !

Nelson Z. @ Teclib'

**Comment by tomolimo** [comment]
Yes, but those three lines don’t show anything ☺

Tomolimo

**Comment by ghost** [comment]
They are considered as "intuitive" in a lot of webapps since those 3 white lines are visually implemented everywhere as the "open a sidenav" thing ! :D
But it's true it's not always that obvious ><

Will try to make GLPi Plugins Frontend better everyday, with other side projects I work on at the company !

Thanks again for your feedback,

Newls

**Comment by tomolimo** [comment]
I agree with you.
When I saw them I tried to click on, but nothing happened ☺

-------- Original message --------
From: Nelson Zamith
Date:22/10/2015 13:40 (GMT+01:00)
To: glpi-project/plugins
Cc: "Moron, Olivier"
Subject: Re: [plugins] Web site is one more time broken with IE10 (#34)

They are considered as "intuitive" in a lot of webapps since those 3 white lines are visually implemented everywhere as the "open a sidenav" thing ! :D
But it's true it's not always that obvious ><

Will try to make GLPi Plugins Frontend better everyday, with other side projects I work on at the company !

Thanks again for your feedback,

Newls
