### ISSUE TITLE
Human ressources some Alert are missing in massive action "link a task"

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/plugins#36]
After the massive action "link a task" for more than one check in the checklist, the alert (Mail) for the first check  of the liste is sent. other alerts (mail) for the next checks will not be sent.

**Comment by FRANCOIS50** [comment]
Have anybody the same problem?

**Comment by ghost** [comment]
@FRANCOIS50 , Hello :)

Sorry for the latency out there, I was working on other of the company's projects,
Please use the [Human Resources Plugin's Issue Tracker](https://github.com/InfotelGLPI/resources/issues) for all the [Human Resources Plugin](https://github.com/InfotelGLPI/resources) related issues !

Regards,
newls (Nelson Zamith, Teclib France)

**Comment by FRANCOIS50** [comment]
This case is now added in the right part of github. You can close this ticket.
Thanks for yoiur help

**Comment by ghost** [comment]
You're welcome @FRANCOIS50 !
Ticket is closed. Don't hesitate to make one of them appear if needed !
