### ISSUE TITLE
Human ressouces - Wrong display

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/plugins#37]
See in the following print screen the buttons to move checks in the checklist attributed to a ressource are availlable. but there is no sence to use them in this situation.
![capture](https://cloud.githubusercontent.com/assets/12511115/10887512/bc180f18-8187-11e5-9a5d-d812b14da9e2.PNG)

**Comment by ghost** [comment]
@FRANCOIS50 , Hello :)

Sorry for the latency out there, I was working on other of the company's projects,
Please use the [Human Resources Plugin's Issue Tracker](https://github.com/InfotelGLPI/resources/issues) for all the [Human Resources Plugin](https://github.com/InfotelGLPI/resources) related issues !

Regards,
newls (Nelson Zamith, Teclib France)
