### ISSUE TITLE
http://plugins.glpi-project.org/ is broken under IE10

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/plugins#38]
Hello,
Here are the errors in the IE debug console:

HTML1300: Navigation occurred. 
http://plugins.glpi-project.org/
SCRIPT1046: Multiple definitions of a property not allowed in strict mode 
scripts.8dbffda7.js, line 1 character 4242
SCRIPT5022: [$injector:modulerr] Failed to instantiate module frontendApp due to:
Error: [$injector:nomod] Module 'frontendApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.4.7/$injector/nomod?p0=frontendApp
   at Anonymous function (http://plugins.glpi-project.org/scripts/vendor.81a16c6c.js:4:10533)
   at b (http://plugins.glpi-project.org/scripts/vendor.81a16c6c.js:4:9993)
   at Anonymous function (http://plugins.glpi-project.org/scripts/vendor.81a16c6c.js:4:10267)
   at Anonymous function (http://plugins.glpi-project.org/scripts/vendor.81a16c6c.js:4:19003)
   at f (http://plugins.glpi-project.org/scripts/vendor.81a16c6c.js:4:1387)
   at n (http://plugins.glpi-project.org/scripts/vendor.81a16c6c.js:4:18846)
   at $a (http://plugins.glpi-project.org/scripts/vendor.81a16c6c.js:4:20534)
   at h (http://plugins.glpi-project.org/scripts/vendor.81a16c6c.js:4:8060)
   at ga (http://plugins.glpi-project.org/scripts/vendor.81a16c6c.js:4:8279)
   at fa (http://plugins.glpi-project.org/scripts/vendor.81a16c6c.js:4:7624)
http://errors.angularjs.org/1.4.7/$injector/modulerr?p0=frontendApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'frontendApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.4.7%2F%24injector%2Fnomod%3Fp0%3DfrontendApp%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.81a16c6c.js%3A4%3A10533)%0A%20%20%20at%20b%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.81a16c6c.js%3A4%3A9993)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.81a16c6c.js%3A4%3A10267)%0A%20%20%20at%20Anonymous%20function%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.81a16c6c.js%3A4%3A19003)%0A%20%20%20at%20f%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.81a16c6c.js%3A4%3A1387)%0A%20%20%20at%20n%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.81a16c6c.js%3A4%3A18846)%0A%20%20%20at%20%24a%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.81a16c6c.js%3A4%3A20534)%0A%20%20%20at%20h%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.81a16c6c.js%3A4%3A8060)%0A%20%20%20at%20ga%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.81a16c6c.js%3A4%3A8279)%0A%20%20%20at%20fa%20(http%3A%2F%2Fplugins.glpi-project.org%2Fscripts%2Fvendor.81a16c6c.js%3A4%3A7624) 
vendor.81a16c6c.js, line 4 character 19171

Thank you,
regards,
Tomolimo

**Comment by ghost** [comment]
Hello,
Thanks again for highlighting that problem,
we fixed that bug, and we'll let you close that Issue for us :)
It may happen again one day, don't hesitate to create another issue, it's ok.

Regards,
Newls

**Comment by tomolimo** [comment]
Hello Newls,
This is ok now, IE10 is working well.
Thank you,
regards,
Tomolimo
