### ISSUE TITLE
clean authors on plugin update 

### ISSUE THREAD

**Issue by orthagh** [glpi-project/plugins#4]
some authors don't have any plugin associated (example old authors of formcreator)

**Comment by ghost** [comment]
https://raw.githubusercontent.com/TECLIB/formcreator/master/plugin.xml in the provided XML file for formcreator, it looks like the formcreator team mentionned Teclib' as only Author. I first thought there was a problem to relink an author of an updated plugin, but I was wrong. Now, if I understand correctly, we want any user with no more plugins to be deleted ? This might not be the adequate policy to opt for, if we encourage old contributors to create an account on the upcoming user panel, we sure don't want any user account to be deleted.

**Comment by orthagh** [comment]
old formcreator plugin xml : https://forge.glpi-project.org/projects/formcreator/repository/entry/formcreator.xml

list of authors : 
- Gonéri Le Bouder
- Nicolas Manceau
- Dimitri Mouillard

new xml contains a unique Teclib.
This morning i updated the plugin xml url so http://vm000140.paas.teclib.net/#/author/36

Howver, your last point is good.
But, it's strange to have 0 plugins authors.
I think, we should, instead, do not show them in authors list

**Comment by ghost** [comment]
I rush on that.
