### ISSUE TITLE
Claim an authorship not working

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/plugins#41]
Hello,
I tried the Claim an authorship feature, but nothing happened: I got an 'We ackownledged your request', but nothing happened after that!
Should I wait for an administrator action, or will it be automatic?
thank you,
regards,
Tomolimo

PS: "ackownledged" should be "acknowledge", with a 'n' after the 'k' and no 'd'.

**Comment by ghost** [comment]
Dear Tomolimo, 
I just seen your request, it has been acknowledged, 
Thank you very much for your support, 
This is your profile public page : I just seen your request, it has been acknowledged 
The system is going to change one day, the concept of 'authors' is going to be replaced by the one of contributor, in a very github-like fashion ! 

You are very welcome if you have any other suggestion, on glpi@teclib.com, or http://suggest.glpi-project.com 

Nelson @Teclib 

Nelson Zamith 
Developer 
GLPI : www.glpi-project.org 
nzamith@teclib .com 
Teclib Telephone Line : +33 1 79 97 02 78 
118, rue de Rivoli - 75001 Paris 
Facebook | Twitter | www.teclib.com 

----- Original Message -----
