### ISSUE TITLE
list of tags show a constant instead of plugins number

### ISSUE THREAD

**Issue by neeftarah** [glpi-project/plugins#46]
![capture-catalogue-plugin](https://cloud.githubusercontent.com/assets/6593470/11741805/a272a87e-9ffb-11e5-99ad-24cf4189c744.png)

**Comment by ghost** [comment]
Thanks for it :)
I just saw it today by the way !
I'm trying to fetch some time to work on glpi-plugin-directory as soon as possible, we're very busy @ Montpellier and all the GLPi Team is also aswell.
