### ISSUE TITLE
Can't submit new plugin

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/plugins#47]
Can't submit new plugin:
Errors in Chrome are:

![image](https://cloud.githubusercontent.com/assets/7569958/13875560/f3e679e2-ecfe-11e5-9eb1-a73e189ffbd5.png)

thank you,
Tomolimo

**Comment by tomolimo** [comment]
up!

**Comment by orthagh** [comment]
Is this issue still valid ?

I tested on local with success, and we have some recent plugin

BTW, sorry for the delay.

**Comment by tomolimo** [comment]
Seems not :)
