### ISSUE TITLE
Plugin display page issue when logged in

### ISSUE THREAD

**Issue by trasher** [glpi-project/plugins#48]
Hi,

The display plugin page has some issues when displayed as logged in user. Here is for example the output in firefox:
![capture d ecran de 2016-09-19 11-41-47](https://cloud.githubusercontent.com/assets/224733/18628059/b3cb0f20-7e5e-11e6-912c-356736f84b95.png)

Display is not the same using chromium; but it is also broken. I did not test on other browsers.

**Comment by orthagh** [comment]
Strange behavior, i don't have the display on my browsers (firefox 49 & chrome 52).

What's your versions ?

**Comment by trasher** [comment]
Same, or almost. I guess this is a size issue (yes, size matters! :D)

**Comment by cedric-anne** [comment]
@trasher 

Can you check if this issue persists ?

Regards

**Comment by trasher** [comment]
Yes, it is
