### ISSUE TITLE
Missing images/logo-small.png causes 404 HTTP error

### ISSUE THREAD

**Issue by C-Duv** [glpi-project/plugins#49]
The following image is required by the application http://plugins.glpi-project.org/images/logo-small.png (see file [`frontend/app/styles/_header.sass`, line 10](https://github.com/glpi-project/plugins/blob/dec0702cbc1113b33dd86facf579deb3ae84c744/frontend/app/styles/_header.sass#L10) but it seems it does not exists causing a 404 HTTP response.

``` Shell
curl -D - -o /dev/null -s http://plugins.glpi-project.org/images/logo-small.png
```

> HTTP/1.1 404 Not Found
> Date: Thu, 29 Sep 2016 14:21:50 GMT
> Content-Type: text/html; charset=iso-8859-1
> Transfer-Encoding: chunked
> Connection: keep-alive
> Set-Cookie: __cfduid=d26bed67a7f87a418e9a07aa008930acb1475158910; expires=Fri, 29-Sep-17 14:21:50 GMT; path=/; domain=.glpi-project.org; HttpOnly
> CF-Cache-Status: HIT
> Server: cloudflare-nginx
> CF-RAY: 2ea0157890d308fc-CDG

(Could be an error on CloudFlare's side)

**Comment by orthagh** [comment]
In progress, our build system break name of images.

logo-small.0b94517b.png instead of logo-small.png

I manually move the name and i'm currently investigating the bug
