### ISSUE TITLE
add rss feeds for new and updated plugins 

### ISSUE THREAD

**Issue by orthagh** [glpi-project/plugins#51]

**Comment by remicollet** [comment]
Of course, for **new plugins** (Most recent in the catalog), but also for **updated plugins** (Recently updated plugins) ;)

**Comment by orthagh** [comment]
@remicollet  http://plugins.glpi-project.org/#/ should now have published feeds.

**Comment by remicollet** [comment]
Thanks a lot !

**Comment by tomolimo** [comment]
There is a small trouble with some dates...
![image](https://cloud.githubusercontent.com/assets/7569958/19354507/38de14bc-9167-11e6-9345-a97bf709d5c2.png)

**Comment by orthagh** [comment]
It should be better.
Please, test again (think to clean your files/_rss directory of your glpi before testing again)

**Comment by tomolimo** [comment]
Perfect, tested and passed, thank you

**Comment by ajsb85** [comment]
Hi @all 

I can see an issue. Is the same `pubDate` of the new plugins:

```XML
<pubDate>Thu, 27 Apr 2017 00:00:00 +0200</pubDate>
<pubDate>Thu, 27 Apr 2017 00:00:00 +0200</pubDate>
```

The root `pubDate` is ok
```XML
<pubDate>Thu, 27 Apr 2017 18:26:37 +0200</pubDate>
```

view-source:http://plugins.glpi-project.org/api/plugin/rss_updated

[rss_updated.zip](https://github.com/glpi-project/plugins/files/963887/rss_updated.zip)
