### ISSUE TITLE
RSS pubDate bug

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/plugins#56]
Dearest.

No time in the `pubDate` of the new plugins:

```XML
<pubDate>Thu, 27 Apr 2017 00:00:00 +0200</pubDate>
<pubDate>Thu, 27 Apr 2017 00:00:00 +0200</pubDate>
```

The root `pubDate `is ok
```XML
<pubDate>Thu, 27 Apr 2017 18:26:37 +0200</pubDate>
```

view-source:http://plugins.glpi-project.org/api/plugin/rss_updated

[rss_updated.zip](https://github.com/glpi-project/plugins/files/963887/rss_updated.zip)

**Comment by ajsb85** [comment]
Alone in the dark :neckbeard:

**Comment by cedric-anne** [comment]
Hi,

This is due to the fact that only dates are stored in `plugin.date_updated` field in DB, so information cannot be more procise.

Regards
