### ISSUE TITLE
Problem with PDF plugin 1.1 on GLPI 9.1.3

### ISSUE THREAD

**Issue by cbedetti1** [glpi-project/plugins#59]
Hi,
The PDF plugin has issues. Even though it is properly installed and activated, no buttons are displayed.
glpi

**Comment by txotxe7** [comment]
Same here!
GLPI 9.1.2 with PDF Plugin 1.1

**Comment by cbedetti1** [comment]
Hi Txotxe,
i've solved! you must login with admin account in GLPI and assign the grant to Admin user and at all users or profile about this plugin.

Good luck
