### ISSUE TITLE
Errors occured during migration

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/plugins#81]
Today, the GLPI was updated with a nightly build from 2022-01-29 00:21:21.
After performing the update, it was necessary to migrate the tables with the command “php bin/console glpi:migration:unsigned_keys” and 1 the table did not migrate and an error was received “Migration of column "glpi_plugin_manageentities_configs.documentcategories_id" cannot be done as it contains negative values.” What value should be set for glpi to perform the migration correctly?
![1](https://user-images.githubusercontent.com/97535165/151779155-0f8f1698-313a-40ce-9b21-032f91cfcaef.png)
![2](https://user-images.githubusercontent.com/97535165/151779161-3bb683cf-07b0-492d-a3a1-7e34496d5e77.png)

**Comment by cedric-anne** [comment]
Hi,

Please open this issue here: https://github.com/InfotelGLPI/manageentities.

Regards
