### ISSUE TITLE
Issue with signglesignon plugin with GLPI 10.0.9

### ISSUE THREAD

**Issue by Sergio1922** [glpi-project/plugins#84]
Hello,
I upgraded from GLPI 10.0.6 to 10.0.9 last saturday.
I ussed to use the plugin singlesignon for google sign in. It worked well with the previous versions og GLPI.
But with the 10.0.9, it is not possible to install the plugin. I can only install the older version 1.1.0.
I use the same setting as i used with the GLPI 10.0.6 version but i get the rerror message URI_mismatch
Thank you for your support
![error glpi](https://github.com/glpi-project/plugins/assets/97602376/ee686d97-d51f-4b9f-85a1-2357bb926154)
![glpi_log](https://github.com/glpi-project/plugins/assets/97602376/7d3279d5-3e89-4817-a7a6-fdab2d090621)

**Comment by cedric-anne** [comment]
Issues here are only related to plugin catalog, not plugins themselves.

I saw you opened an issue in the plugin repository, it is probably the right place to do it (see https://github.com/edgardmessias/glpi-singlesignon/issues/71).
